### ISSUE TITLE
Adventure Kit 30 Days Challenge

### ISSUE THREAD

**Issue by marysaray** [marysaray/30DaysLostInSpace#1]
- [ ] Day 1: Incoming Broadcast from InventrCorp
- [ ] Day 2: It's really dark in here...
- [ ] Day 3: I'm worried about your battery levels
- [ ] Day 4: Cabin Lighting
- [ ] Day 5: Creative Day #1
- [ ] Day 6: Time to fix the battery
- [ ] Day 7: We still need to keep an eye on this
- [ ] Day 8: Adding some color to this dark place
- [ ] Day 9: A better way to do things
- [ ] Day 10: Creative Day #2
- [ ] Day 11: Starting your control panel
- [ ] Day 12: Can you hear us?
- [ ] Day 13: HERO Security 101
- [ ] Day 14: Advanced security panel
- [ ] Day 15: Creative Day #3
- [ ] Day 16: A fancy new display
- [ ] Day 17: H jyfwapj tlzzhnl
- [ ] Day 18: The surface seems so much closer
- [ ] Day 19: New Horizons
- [ ] Day 20: Creative Day #4
- [ ] Day 21: Hello New World
- [ ] Day 22: Display Panel Details
- [ ] Day 23: Launch System
- [ ] Day 24: Back to Orbit
- [ ] Day 25: Creative Day #5
- [ ] Day 26: HERO_AUTOPILOT.EXE (Fun W/Bitmaps)
- [ ] Day 27: HERO_AUTOPILOT.EXE Part 2
- [ ] Day 28: Landing Gear
- [ ] Day 29: Landing Gear Part 2
- [ ] Day 30: Home Sweet Home! (Mission Complete!
![LostInSpaceIntro](https://user-images.githubusercontent.com/82470838/219909891-56a2d47a-78aa-46fd-8c39-d45bdfa1a43d.jpg)
)
